apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  labels:
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
        version: v1
    spec:
      containers:
      - name: inventory-api
        image: betamedina/inventory-api:latest
        ports:
        - containerPort: 8010
