apiVersion: v1
kind: Service
metadata:
  name:  price-api-lb
  labels:
    app: price-api-lb
spec:
  type:  LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
  selector:
    app:  price-api
    env:  green