apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  labels:
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
        version: v1
    spec:
      containers:
      - name: inventory-api
        image: betamedina/inventory-api:latest
        ports:
        - containerPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  name:  inventory-api-lb
  labels:
    app: inventory-api-lb
spec:
  type:  LoadBalancer
  ports:
    - protocol: TCP
      port: 8010
  selector:
    app:  inventory-api
