apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  labels:
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
        version: v1
    spec:
      containers:
      - name: product-api
        image: betamedina/product-api:latest
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name:  product-api-lb
  labels:
    app: product-api-lb
spec:
  type:  LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
  selector:
    app:  product-api
